package org.manisoft.dialogs;

import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import org.manisoft.entities.EnrolledCourse;

/**
 *
 * @author manianis
 */
public class DialogGrades extends DialogBase<EnrolledCourse> {
    
    private ArrayList<JTextField> txtGrades = new ArrayList<>();

    /**
     * Creates new form DialogStudent
     *
     * @param parent
     * @param opType
     */
    public DialogGrades(Frame parent, OperationType opType) {
        super(parent, opType);
        initComponents();
        getRootPane().setDefaultButton(okBtn);
    }
    
    @Override
    public void setData(EnrolledCourse data) {
        super.setData(data);
        if (data == null) {
            return;
        }
        
        JLabel label = new JLabel("Grades");
        GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(label, gridBagConstraints);
        
        for (int i = 0; i < data.getGradesCount(); i++) {
            JTextField txtGrade = new JTextField();
            txtGrades.add(txtGrade);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1 + i % 3;
            gridBagConstraints.gridy = 3 + i / 3;
            gridBagConstraints.ipadx = 2;
            gridBagConstraints.ipady = 2;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
            getContentPane().add(txtGrade, gridBagConstraints);
        }
        int lines = data.getGradesCount() / 3
                + (data.getGradesCount() % 3 != 0 ? 1 : 0);
        setSize(getWidth(),
                250 + (txtCourse.getHeight() + 4) * lines);
        updateInterface();
    }
    
    @Override
    public void updateInterface() {
        txtCourse.setText(data.getCourse().toString().trim());
        txtStudent.setText(data.getStudent().toString().trim());
        if (txtGrades.size() == data.getGradesCount()) {
            for (int i = 0; i < data.getGradesCount(); i++) {
                txtGrades.get(i).setText("" + data.getGrade(i));
            }
        }
    }
    
    @Override
    public void updateData() {
        for (int i = 0; i < txtGrades.size(); i++) {
            JTextField txtField = txtGrades.get(i);
            int grade = Integer.parseInt(txtField.getText());
            data.setGrade(i, grade);
        }
    }
    
    @Override
    public boolean isValidData() {
        for (int i = 0; i < txtGrades.size(); i++) {
            JTextField txtField = txtGrades.get(i);
            boolean error = false;
            try {
                int grade = Integer.parseInt(txtField.getText());
                error = (grade < 0 || grade > 100);
            } catch (NumberFormatException e) {
                error = true;
            }
            if (error) {
                txtField.requestFocus();
                JOptionPane.showMessageDialog(null,
                        "Given grades should be between 0 and 100.",
                        "Invalid data", JOptionPane.OK_OPTION);
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        labelCourse = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        lblStudent = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {80, 80, 80, 80};
        layout.columnWeights = new double[] {1.0, 1.0, 1.0, 1.0};
        layout.rowWeights = new double[] {1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0};
        getContentPane().setLayout(layout);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Students Grades");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblTitle, gridBagConstraints);

        labelCourse.setText("Course");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelCourse, gridBagConstraints);

        txtCourse.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtCourse, gridBagConstraints);

        lblStudent.setText("Student");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblStudent, gridBagConstraints);

        txtStudent.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtStudent, gridBagConstraints);

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(okBtn, gridBagConstraints);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(cancelBtn, gridBagConstraints);

        setBounds(0, 0, 410, 163);
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        acceptChanges();
    }//GEN-LAST:event_okBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        cancelChanges();
    }//GEN-LAST:event_cancelBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel labelCourse;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtStudent;
    // End of variables declaration//GEN-END:variables
}
